services:
  app:
    command: sh -c "npm run dev -- --host"
    image: node:21
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /App
    volumes:
      - ./App:/App
  server:
    build: python3
    ports:
      - 127.0.0.1:5000:5000
    volumes:
        - ./RESTAPI:/server
    stdin_open: true
    tty: true
    command: sh -c "python -m venv .venv && . .venv/bin/activate && cd server && pip install -r requirements.txt && flask run --host=0.0.0.0"